enum ResponseCode {

  // HTTP STATUS 200
  SUCCESS = "SU",
  LOGIN_SUCCESS = "LS",
  DONATION_SUCCESS = "DS",

  // HTTP STATUS 201
  SIGN_UP_SUCCESS = "SUS",

  // HTTP STATUS 400
  DUPLICATED_LOGIN_ID = "DLI",
  DUPLICATED_NICKNAME = "DN",
  NO_EXISTED_MEMBER = "NEM",
  VALIDATION_FAILED = "VF",
  NO_EXISTED_STATION = "NES",
  NO_EXISTED_BOARD = "NB",
  PASSWORD_MISMATCH = 'PM',

  //HTTP STATUS 401
  LOGIN_FAILED = "LF",
  NO_PERMISSION_TOKEN = "NPT",
  AUTHORIZATION_FAIL = "AF",

  //HTTP STATUS 500
  DATABASE_ERROR = "DBE",

}

export default ResponseCode;