export const MAIN_CATEGORIES = [
  {value :'ALL',label: '전체'},
  { value: 'JAVA', label: 'Java' },
  { value: 'PYTHON', label: 'Python' },
  { value: 'JAVASCRIPT', label: 'JavaScript' },
  { value: 'CPP', label: 'C++' },
  { value: 'CSHARP', label: 'C#' },
  { value: 'TYPESCRIPT', label: 'TypeScript' },
  { value: 'GO', label: 'Go' },
  { value: 'RUST', label: 'Rust' },
  { value: 'SWIFT', label: 'Swift' },
  { value: 'KOTLIN', label: 'Kotlin' },
  { value: 'PHP', label: 'PHP' },
  { value: 'RUBY', label: 'Ruby' },
  { value: 'C', label: 'C' },
  { value: 'SCALA', label: 'Scala' },
  { value: 'DART', label: 'Dart' },
  { value: 'LUA', label: 'Lua' },
  { value: 'R', label: 'R' },
  { value: 'HTML', label: 'HTML' },
  { value: 'CSS', label: 'CSS' },
  { value: 'SQL', label: 'SQL' },
];