spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/live_stream?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dudwns1641@

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  payment :
    api-key : "4816558854634321"
    secret-key : "qAaiormyWKeCUIbQMUM2Gll8qNDrAxj3wsUlb08CyJprT1Q5ODed0Dhb6GYnZ5k0FY6EodorCVA06EEU"


  jwt:
    secret: testtesttest
    token:
      access-expiration-time: 3600000    # 1 hour in milliseconds
      refresh-expiration-time: 604800000   # 7 days in milliseconds

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  file :
    boardImagesPath : "/Users/gim-yeongjun/Desktop/2024-feedback/livefeedback/boardImages/"
    thumbnailPath : "/Users/gim-yeongjun/Desktop/2024-feedback/livefeedback/thumbnails/"
    profilePath : "/Users/gim-yeongjun/Desktop/2024-feedback/livefeedback/profileImages/"

    boardImagesUrl : "http://localhost:8080/file/boardImages"
    thumbnailUrl : "http://localhost:8080/file/thumbnail/"
    profileUrl : "http://localhost:8080/file/profile/"

logging:
  level:
    org.springframework.security: DEBUG